mjcf_list:
  - xml/franka_emika_panda/panda.xml

renderer_list:
  - renderer: maniskill
    benchmark_script: benchmark_maniskill.py
    timeout: 120

rasterizer_list:
  - true

batch_size_list:
  - 1
  - 2
  - 4
  - 8
  - 16
  - 32
  - 64
  - 128
  - 256
  - 512
  - 768
  - 1024
  - 2048

resolution_list:
  #square:
  - [128, 128]
  - [256, 256]
  
  #four_three:
  
  #sixteen_nine:

comparison_list:
  - - renderer: maniskill
      rasterizer: true

# Configurations shared betwen batch_benchmark.py and benchmark_*.py
# Raytracer configuration
raytracer:
  max_bounce: 2
  spp: 1

# Simulation configuration
simulation:
  n_steps: 100

# Camera configuration
camera:
  position: [1.5, 0.5, 1.5]  # [x, y, z]
  lookat: [0.0, 0.0, 0.5]    # [x, y, z]
  fov: 45.0                  # degrees

# Display configuration
display:
  gui: false  # Enable/disable GUI mode
